### ISSUE TITLE
Error when building efi

### ISSUE THREAD

**Issue by Verhulstak** [lzhoang2801/OpCore-Simplify#11]
i got this error:
####################################################################
#                        An Error Occurred                         #
####################################################################

Traceback (most recent call last):
  File "D:\Downloads\OpCore-Simplify-main\OpCore-Simplify.py", line 300, in <module>
    o.main()
  File "D:\Downloads\OpCore-Simplify-main\OpCore-Simplify.py", line 289, in main
    self.build_opencore_efi(hardware_report, unsupported_devices, smbios_model, macos_version)
  File "D:\Downloads\OpCore-Simplify-main\OpCore-Simplify.py", line 120, in build_opencore_efi
    acpi_load = getattr(self.ac, patch.function_name)()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Report.json](https://github.com/user-attachments/files/17344326/Report.json)
^^^^^
  File "D:\Downloads\OpCore-Simplify-main\Scripts\acpi_guru.py", line 2544, in instant_wake_fix
    if binascii.unhexlify(gprw_method) in self.dsdt.get("raw"):
                                          ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

Press Enter to continue...
i provided my json, also its the newst version i think since i downloaded it like 20 minutes ago

**Comment by Verhulstak** [comment]
github kinda put the json in a weird plase when i dragged it so i apologize
