### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by vendor-dlkm** [lzhoang2801/OpCore-Simplify#13]
```
Traceback (most recent call last):
  File "C:\Users\vendor_dlkm\Desktop\OPCS\OpCore-Simplify-main\OpCore-Simplify.py", line 300, in <module>
    o.main()
    ~~~~~~^^
  File "C:\Users\vendor_dlkm\Desktop\OPCS\OpCore-Simplify-main\OpCore-Simplify.py", line 289, in main
    self.build_opencore_efi(hardware_report, unsupported_devices, smbios_model, macos_version)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vendor_dlkm\Desktop\OPCS\OpCore-Simplify-main\OpCore-Simplify.py", line 120, in build_opencore_efi
    acpi_load = getattr(self.ac, patch.function_name)()
  File "C:\Users\vendor_dlkm\Desktop\OPCS\OpCore-Simplify-main\Scripts\acpi_guru.py", line 1578, in add_system_management_bus_device
    pci_bus_device = ".".join(self.lpc_bus_device.split(".")[:2])
```

**Comment by lzhoang2801** [comment]
Make sure the ACPI tables are present in the ACPITables folder, and that you're using the correct path to the ACPITables folder. Dumping the ACPITables again is also a temporary solution until I can check the error accurately

**Comment by vendor-dlkm** [comment]
I did check that the necessary .aml files are present and also checked that I'm using the correct path. Tried dumping the tables again too, but made no difference.

Forgot to mention that it fails to load the ACPI tables in the Hardware Report step, but lets me continue the setup until I get the same error I mentioned above.

```
Please drag and drop ACPI Tables folder here: C:\Users\vendor_dlkm\Desktop\OPCS\HS\Results\ACPITables
Gathering valid tables from ACPITables...

 - apic.aml
 - dsdt.aml
 - ssdt1.aml
 - ssdt2.aml
 - ssdt3.aml
 - ssdt4.aml
 - ssdt5.aml
 - ssdt.aml

Disassembling dsdt.aml to verify if pre-patches are needed...

Disassembled successfully!

Loading valid tables in C:\Users\vendor_dlkm\Desktop\OPCS\HS\Results\ACPITables...

Failed to load tables in C:\Users\vendor_dlkm\Desktop\OPCS\HS\Results\ACPITables:

 - apic.aml
 - ssdt1.aml
 - ssdt2.aml
 - ssdt3.aml
 - ssdt4.aml
 - ssdt5.aml
 - ssdt.aml

Press Enter to continue...
```

**Comment by lzhoang2801** [comment]
Please try again with the latest commit and let me know the result

**Comment by vendor-dlkm** [comment]
There's no error in loading the ACPI tables or creating the EFI anymore. Issue's solved. 👍
