### ISSUE TITLE
Not able to run application

### ISSUE THREAD

**Issue by lcsjandrey** [lzhoang2801/OpCore-Simplify#17]
This is the following error message that i receive when trying to open the application on Windows 10:

```
####################################################################
#                        Check for Updates                         #
####################################################################

Current script SHA version: e808e502ae8bc76993a1e41826d6f94a88a3bfea
Latest script SHA version: e808e502ae8bc76993a1e41826d6f94a88a3bfea

You are already using the latest version
SSL Context Creation Error: No module named 'certifi'
SSL Context Creation Error: No module named 'certifi'
SSL Context Creation Error: No module named 'certifi'
An error occurred :(
 - Could not get latest iasl for Windows
Traceback (most recent call last):
  File "C:\Users\t5810\Desktop\OpCore-Simplify-main\OpCore-Simplify.py", line 336, in <module>
    o = OCPE()
        ^^^^^^
  File "C:\Users\t5810\Desktop\OpCore-Simplify-main\OpCore-Simplify.py", line 22, in __init__
    self.ac = acpi_guru.ACPIGuru()
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t5810\Desktop\OpCore-Simplify-main\Scripts\acpi_guru.py", line 19, in __init__
    self.acpi = dsdt.DSDT()
                ^^^^^^^^^^^
  File "C:\Users\t5810\Desktop\OpCore-Simplify-main\Scripts\dsdt.py", line 36, in __init__
    raise Exception(exception)
Exception: Could not locate or download iasl!

Please manually download and extract iasl.exe and acpidump.exe from:
 - https://www.intel.com/content/www/us/en/developer/topic-technology/open/acpica/download.html

And place in:
 - C:\Users\t5810\Desktop\OpCore-Simplify-main\Scripts

```
No issues are found are performed the task.

**Comment by lzhoang2801** [comment]
```
Exception: Could not locate or download iasl!

Please manually download and extract iasl.exe and acpidump.exe from:
 - https://www.intel.com/content/www/us/en/developer/topic-technology/open/acpica/download.html

And place in:
 - C:\Users\t5810\Desktop\OpCore-Simplify-main\Scripts
```

**Comment by lzhoang2801** [comment]
Fixed https://github.com/lzhoang2801/OpCore-Simplify/commit/81fe73dd03b1584cc8fa143e04a6f14536d42047
