### ISSUE TITLE
Cannot access local variable 'supported_audio' where it is not associated with a value

### ISSUE THREAD

**Issue by g2david** [lzhoang2801/OpCore-Simplify#49]
####################################################################
#                        An Error Occurred                         #
####################################################################

Traceback (most recent call last):
  File "C:\Users\home\Downloads\OpCore-Simplify-main\OpCore-Simplify.py", line 347, in <module>
    o.main()
    ~~~~~~^^
  File "C:\Users\home\Downloads\OpCore-Simplify-main\OpCore-Simplify.py", line 306, in main
    native_macos_version, hardware_report, unsupported_devices, needs_oclp, ocl_patched_macos_version = self.c.check_compatibility(hardware_report)
                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\home\Downloads\OpCore-Simplify-main\Scripts\compatibility_checker.py", line 330, in check_compatibility
    function()
    ~~~~~~~~^^
  File "C:\Users\home\Downloads\OpCore-Simplify-main\Scripts\compatibility_checker.py", line 192, in check_sound_compatibility
    supported_audio[audio_device] = audio_props
    ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'supported_audio' where it is not associated with a value



Press Enter to continue...




[Report.json](https://github.com/user-attachments/files/17681269/Report.json)

**Comment by lzhoang2801** [comment]
Fixed
