### ISSUE TITLE
Build OpenCore EFI problem (python script related?)

### ISSUE THREAD

**Issue by mattximac** [lzhoang2801/OpCore-Simplify#60]
I had already MacOS installed on this computer (different versions) and all of them worked fine.
At the time i created my EFI manually (with OpenCore) but after installing windows again i unfortunately deleted my created EFI (with all kext, configuration, etc.) so i wanted to test your script (to save time) but ......

After choosing the last option (6) to create the EFI i see this error message:

"**Traceback (most recent call last):
  File "C:\Users\Matt\Desktop\OpCore-Simplify-main\OpCore-Simplify.py", line 349, in <module>
    o.main()
    ~~~~~~^^
  File "C:\Users\Matt\Desktop\OpCore-Simplify-main\OpCore-Simplify.py", line 338, in main
    self.build_opencore_efi(hardware_report, unsupported_devices, smbios_model, macos_version, needs_oclp)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\Desktop\OpCore-Simplify-main\OpCore-Simplify.py", line 162, in build_opencore_efi
    acpi_load = getattr(self.ac, patch.function_name)()
  File "C:\Users\Matt\Desktop\OpCore-Simplify-main\Scripts\acpi_guru.py", line 1047, in fix_system_clock_awac
    comment += " - Requires {} Rename".format(", ".join(suffix))
    ^^^^^^^
UnboundLocalError: cannot access local variable 'comment' where it is not associated with a value**"

**Comment by mattximac** [comment]
No i see it's commented out in the script :) Sorry! Thank you.
