### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by inLnx** [lzhoang2801/OpCore-Simplify#77]
When trying to run I get this error
`Traceback (most recent call last):
  File "C:\Users\youtu\Downloads\OpCore-Simplify-main\OpCore-Simplify.py", line 2, in <module>
    from Scripts import acpi_guru
  File "C:\Users\youtu\Downloads\OpCore-Simplify-main\Scripts\acpi_guru.py", line 7, in <module>
    from Scripts import smbios
  File "C:\Users\youtu\Downloads\OpCore-Simplify-main\Scripts\smbios.py", line 3, in <module>
    from Scripts import gathering_files
  File "C:\Users\youtu\Downloads\OpCore-Simplify-main\Scripts\gathering_files.py", line 1, in <module>
    from Scripts import github
  File "C:\Users\youtu\Downloads\OpCore-Simplify-main\Scripts\github.py", line 1, in <module>
    from Scripts import resource_fetcher
  File "C:\Users\youtu\Downloads\OpCore-Simplify-main\Scripts\resource_fetcher.py", line 8, in <module>
    from urllib.request import urlopen, Request
  File "C:\Users\youtu\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 88, in <module>
    import http.client
  File "C:\Users\youtu\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Users\youtu\AppData\Local\Programs\Python\Python313\Lib\email\parser.py", line 12, in
 <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Users\youtu\AppData\Local\Programs\Python\Python313\Lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Users\youtu\AppData\Local\Programs\Python\Python313\Lib\email\_policybase.py", line 7, in <module>
    from email import header
  File "C:\Users\youtu\AppData\Local\Programs\Python\Python313\Lib\email\header.py", line 16, in
 <module>
    import email.quoprimime
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1155, in get_code
  File "<frozen importlib._bootstrap_external>", line 784, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
`

**Comment by lzhoang2801** [comment]
Please ensure Python is installed correctly. This is an error related to compiled bytecode files (.pyc files).

**Comment by inLnx** [comment]
I just did a fresh install

**Comment by lzhoang2801** [comment]
Try running a different Python program to see if it works

**Comment by alebypegasus** [comment]
I also have this same problem, I’ve already changed Python and it didn’t work, does anyone know of any solution?

**Comment by spakk** [comment]
Regardless of whether I run the OpCore-Simplify.bat file with or without administrator rights, I receive this error message when selecting :
"1. Select Hardware Report" and attempting to export the hardware report.
What is the cause, and how can I proceed to successfully export the hardware report?

`Hardware Report: No report selected

1. Select Hardware Report
2. Select macOS Version
3. Customize ACPI Patch
4. Customize Kexts
5. Customize SMBIOS Model
6. Build OpenCore EFI

Q. Quit

Select an option:`


Error Report:
`####################################################################
#                        An Error Occurred                         #
####################################################################

Traceback (most recent call last):
  File "C:\Users\User\Desktop\OpCore-Simplify-main\OpCore-Simplify.py", line 351, in <module>
    o.main()
    ~~~~~~^^
  File "C:\Users\User\Desktop\OpCore-Simplify-main\OpCore-Simplify.py", line 307, in main
    hardware_report_path, hardware_report = self.select_hardware_report()
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\Desktop\OpCore-Simplify-main\OpCore-Simplify.py", line 82, in select_hardware_report
    data = self.u.read_file(path)
  File "C:\Users\User\Desktop\OpCore-Simplify-main\Scripts\utils.py", line 34, in read_file
    with open(file_path, "r" if file_extension == ".json" else "rb") as file_handle:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\User\\Desktop\\OpCore-Simplify-main'

Press Enter to continue...`

**Comment by 9362180** [comment]
I have the same thing. How to fix it?
![Screenshot 2025-01-09 152141](https://github.com/user-attachments/assets/10f1b7d9-c93d-460b-8f74-08e23e84080d)

**Comment by alebypegasus** [comment]
Something you are plugging into the PC that is giving conflict, uncheck NullEternet and see if it fixes it, because it must be down.
