### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by italiano-sz** [lzhoang2801/OpCore-Simplify#81]
![Zrzut ekranu (1)](https://github.com/user-attachments/assets/855b93f9-9336-4fa1-b36d-fe2f231cca6f)
i got this issue, whiat is it

**Comment by lzhoang2801** [comment]
Try again

**Comment by italiano-sz** [comment]
I've been trying for an hour now and still the same

**Comment by crouchingshinobi** [comment]
![Screenshot 2024-12-19 141232](https://github.com/user-attachments/assets/391fa26b-97b0-414a-b976-c91c4edd2fe6)
I'm having the same issue. Any suggestions? Should I roll back to a different commit?

**Comment by italiano-sz** [comment]
I solved it. Install Python 3.13.0 version and it should work

**Comment by crouchingshinobi** [comment]
![Screenshot 2024-12-19 145943](https://github.com/user-attachments/assets/3667d8ba-1693-4031-8b42-9f192f9e1f79)
Well, it still isn't working. Any other dependencies I might be missing?

**Comment by PyKestrel** [comment]
Any updates on this? I have a fresh Windows install with Python 3.13.0 installed and I'm receiving the same error as originally mentioned.

**Comment by D7my2001** [comment]
Any solution guys?

**Comment by D7my2001** [comment]
Guys, I know the solution. You must extract the zip file ((to the desktop)).

**Comment by Mandaraxa** [comment]
Extracted to desktop, the same error. I think it needs a new reviewed version.

**Comment by 5T33Z0** [comment]
Same for me. Not working in macOS Sonoma+.

**Comment by nunoalves0007** [comment]
same for me

**Comment by lzhoang2801** [comment]
@Mandaraxa @PyKestrel @5T33Z0 @D7my2001 Please redownload OpCore Simplify and check it for me

**Comment by Mandaraxa** [comment]
Sorry, this is the same for me
![SCR-20250106-jkau](https://github.com/user-attachments/assets/15475157-6bd6-4b87-b386-f5f6a51d81d9)

**Comment by Mandaraxa** [comment]
These are my specs:
 Intel i3, 8400, 3.60 GHz, 6M L3 cache; Gigabyte GA-Z370P D3, LGA 1151, Realtek ALC 887 audio codec, 1 x Realtek GbE LAN chip (10/100/1000 Mbit), XFX Radeon RX 580, 8G VRAM, Apple wired aluminum keyboard; macOS 15.X Sequoia with OCLP. SMBIOS = iMac 19.1.

**Comment by SolaceFZ** [comment]
I have the same issue as [this](https://github.com/lzhoang2801/OpCore-Simplify/issues/87) but it was marked as duplicate.
```
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\OpCore-Simplify-main\OpCore-Simplify.py", line 351, in <module>
    o.main()
    ~~~~~~^^
  File "C:\Users\Admin\Desktop\OpCore-Simplify-main\OpCore-Simplify.py", line 339, in main
    self.gathering_files(macos_version)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\OpCore-Simplify-main\OpCore-Simplify.py", line 38, in gathering_files
    self.o.gather_bootloader_kexts(self.k.kexts, macos_version)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\OpCore-Simplify-main\Scripts\gathering_files.py", line 183, in gather_bootloader_kexts
    self.utils.extract_zip_file(zip_path)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Admin\Desktop\OpCore-Simplify-main\Scripts\utils.py", line 114, in extract_zip_file
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
         ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\zipfile\__init__.py", line 1362, in __init__
    self.fp = io.open(file, filemode)
              ~~~~~~~^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\tmpqlzskcc5\\NullEthernet.zip'
```

**Comment by Davi-D-Lucca** [comment]
When clicking to get EFI, it is giving this error 

![Captura de tela 2025-01-06 194443](https://github.com/user-attachments/assets/5a7ca0a2-2b71-42c4-84ee-bb703074736c)

**Comment by 5T33Z0** [comment]
```bash
SHA version information is missing in the sha_version.txt file.

Traceback (most recent call last):
  File "/Users/5t33y0/Downloads/OpCore-Simplify-main/OpCore-Simplify.py", line 344, in <module>
    update_flag = updater.Updater().run_update()
  File "/Users/5t33y0/Downloads/OpCore-Simplify-main/updater.py", line 61, in run_update
    latest_sha_version = self.get_latest_sha_version()
  File "/Users/5t33y0/Downloads/OpCore-Simplify-main/updater.py", line 29, in get_latest_sha_version
    latest_commit = self.github.get_latest_commit("lzhoang2801", "OpCore-Simplify") or {}
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/5t33y0/Downloads/OpCore-Simplify-main/Scripts/github.py", line 15, in get_latest_commit
    raise ValueError("Failed to fetch commit information from GitHub.")
ValueError: Failed to fetch commit information from GitHub.
```

**Comment by imalginov** [comment]
SHA version information is missing in the sha_version.txt file.

Traceback (most recent call last):
  File "/Users/imalginov/Desktop/OpCore-Simplify-main/OpCore-Simplify.py", line 344, in <module>
    update_flag = updater.Updater().run_update()
  File "/Users/imalginov/Desktop/OpCore-Simplify-main/updater.py", line 61, in run_update
    latest_sha_version = self.get_latest_sha_version()
  File "/Users/imalginov/Desktop/OpCore-Simplify-main/updater.py", line 29, in get_latest_sha_version
    latest_commit = self.github.get_latest_commit("lzhoang2801", "OpCore-Simplify") or {}
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/imalginov/Desktop/OpCore-Simplify-main/Scripts/github.py", line 15, in get_latest_commit
    raise ValueError("Failed to fetch commit information from GitHub.")
ValueError: Failed to fetch commit information from GitHub.

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by imalginov** [comment]
Ребята, вообщем намучился я, но решил проблему, во всем виновата Windows 10,11
были 3 сборки windows и только на 3 все удачно получилось, не знаю почему но python вставал криво, что и врезультате получали ошибки. На mac os sonoma просто переустановил 3.13.0 а так же ProperTree и сопоставил пути выбрав 2 пункт. И УРА все заработало!!!!

Guys, I suffered a lot, but I solved the problem, Windows 10.11 was to blame for everything
, there were 3 builds of windows and only 3 succeeded, I don't know why, but python got crooked, which resulted in errors. On mac os, sonoma simply reinstalled 3.13.0 as well as ProperTree and mapped the paths by selecting the 2nd item. Hooray, it's working!!!!

**Comment by aychupkar** [comment]
For people getting the `FileNotFoundError` for `NullEthernet.zip` it seems that the download step for the file (with the URL: 
https://bitbucket.org/RehabMan/os-x-null-ethernet/downloads/RehabMan-NullEthernet-2016-1220.zip) is failing with an SSL error. The code seems to be downloading the file using urllib. I patched the code by changing `Scripts/resource_fetcher.py` and changed the following line:

https://github.com/lzhoang2801/OpCore-Simplify/blob/ff9a51d2504cde6c9a9199bc23de208068b7ada1/Scripts/resource_fetcher.py#L27

To:

```
return urlopen(Request(resource_url, headers=self.request_headers), context=ssl.create_default_context(cafile=certifi.where()))
```

At the top of the file I added these two imports:
```
import certifi
import ssl
```

Note that you will need to install certifi for this to work by running `python -m pip install certifi`

**Comment by lzhoang2801** [comment]
@Mandaraxa @velllum @PyKestrel @SolaceFZ @5T33Z0 Please help me double-check this again

**Comment by 5T33Z0** [comment]
@lzhoang2801 I think that fixed it! It's working in macOS 15.3:

![Bildschirmfoto 2025-01-11 um 14 51 10](https://github.com/user-attachments/assets/c7e2620e-dc92-4a1e-95e8-196a263aefe7)

**Comment by 5T33Z0** [comment]
@bestal42 What the script doesn't tell you: you _MUST_ generate the hardware report (the  `.json` file) in Windows first, because windows provides all the info about the hardware! Only if you have that report already, _then_ you can use it in macOS! 

In other words: the macOS version should contain that vital piece of information that WINDOWS is required to get that report!
